### ISSUE TITLE
Update wallet currencies data

### ISSUE THREAD

**Issue by PaulThblt** [BKFPML/fundamental-app#66]
### _NOTE: This is a server task

**Definition of Done:**

- [x] Function to get the Metadata of each token address 
- [x] Function to get token balance and token address 
- [x] Function to get ETH token balance due to exception
- [x] Connection with the DB and exchange with it to reduce call on the server and optimize the DB space 
- [x] Return the data get to the client if request is made one the server with this object:
```
{
   token_address: <string>
   balance: <int>
}[]
```
- [x]  Creation of a database function who would with the data of the DB return the 'total wallet amount' value for each user

**Comment by KentinPaille** [comment]
Need this to be done to complete the second part and update the first one:
- https://github.com/BKFPML/fundamental-app/issues/87
- https://github.com/BKFPML/fundamental-app/issues/88
