### ISSUE TITLE
Get token price in eur

### ISSUE THREAD

**Issue by KentinPaille** [BKFPML/fundamental-app#87]
**🗒️ Describe the task**
We need a way to get the price of any cryptocurrencies.

**🛠️ Ressources**
[Chainlink price feeds](https://docs.chain.link/data-feeds/price-feeds)

**✅ Definition of Done**

- [x] Function who's able to get the price of any cryptocurrencies
- [x] Store the price inside the DB using supabase

**Comment by verschhh** [comment]
https://freecurrencyapi.com/
https://github.com/fawazahmed0/exchange-api?tab=readme-ov-file
Sur alchemy les currrency sont en USD, est ce qu'il y a une raison particulière pour le price en EUR?
J'ai trouvé cette API qui fait jusqu'à 5K requête par mois, ce qui devrait suffire pour le moment mais du coup soit + de recherche soit + de frais à un certains moment?
Ou bien ce Répo
