### ISSUE TITLE
Crontable to fill the DB

### ISSUE THREAD

**Issue by verschhh** [BKFPML/fundamental-app#96]
**🗒️ Describe the task**
Create a cron that calls for the #87 function every hour, it aims to update the value column in the token_list table and the value  column in the exchange_rate table
**🛠️ Ressources**
https://docs.netlify.com/functions/scheduled-functions/ 
**✅ Definition of Done**

- [x] Set-up the cron

- [x] #71 to be closed first
- [x] Fill the value column in the token_list 

- [x] Fill the value  column in the exchange_rate table

**Comment by KentinPaille** [comment]
@verschhh what issue are you waiting to be done ?

**Comment by verschhh** [comment]
> @verschhh what issue are you waiting to be done ?

? what issue i'm working on?

**Comment by verschhh** [comment]
- [ ] #71 to be closed first
